Updated files.py Check path is a file before opening.
Pythagora-io/gpt-pilot pull request #406
Opened 2023-12-23 08:10 UTC by FuzTheCat

Mandus on Discord supplied the fix with help from ChatGPT-4.

2023-12-23 22:51 UTC, LeonOstrez commented
can you please make PR to "development" branch and not "main". Thank you

2023-12-24 09:03 UTC, senko commented
Rebasing on top of development branch.

2023-12-24 09:18 UTC, senko requested changes
Thanks for contributing the PR! :pray:

There's a couple of things that aren't required (I guess ChatGPT has a bit different style of coding eg dict/Dict, Path/os.path). The important thing is raising ValueError so the rest of the code knows to ignore the file.

If you'd like to rework it a bit to remove extra (unneccessary) changes and just handle the opening problem (my preference would be via catching an Exception but the isfile check is also good), that would be great!

2023-12-24 09:18 UTC, senko commented on pilot/helpers/files.py
> +from typing import Optional, Union, Dict
Using `Dict`, `List`, etc [is deprecated](https://peps.python.org/pep-0585/#implementation) and from 3.9 (which is the minimal version we support), `dict`, etc should be used

2023-12-24 09:18 UTC, senko commented on pilot/helpers/files.py
> +    full_path = os.path.normpath(os.path.join(project_root_path, path))
Hmmm, `path` here should already be full path, adding these two together will probably not work.

2023-12-24 09:18 UTC, senko commented on pilot/helpers/files.py
> +    if not os.path.isfile(full_path):
It'd be better to do this as a general `except Exception` below so it can catch any other errors that might happen (eg. permission error, etc).

2023-12-24 09:18 UTC, senko commented on pilot/helpers/files.py
> +        with open(full_path, "r", encoding="utf-8") as file:
This change has no effect.

2023-12-24 09:18 UTC, senko commented on pilot/helpers/files.py
> +        with open(full_path, "rb") as file:
This change has no effect.

2023-12-24 09:18 UTC, senko commented on pilot/helpers/files.py
> +    relative_path = os.path.relpath(os.path.dirname(full_path), project_root_path)
This change has no effect.

2023-12-26 08:57 UTC, merged